bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 a-c 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 a-p 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 a-r 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 c-a 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 c-p 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 c-r 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 p-a 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 p-c 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 p-r 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 r-a 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 r-c 3
bash scripts/cdusource/main_cdusource.sh officehome b32_ep20_officehome CDUSOURCE ViT-L/14 4 r-p 3