INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "DomainNet"
  # domains = ["clipart", "infograph", "painting", "quickdraw", "real", "sketch"]
  SOURCE_DOMAINS: ["clipart"]


  TARGET_DOMAINS: ["infograph"]

# you can modify the code to explore four domains